apiVersion: v1
kind: Service
metadata:
  name: streamlit-chatbot
spec:
  type: LoadBalancer  # Use NodePort if you're running locally
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: streamlit-chatbot

